//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpyCamera.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpyCamera.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spy Camera.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back Camera.
        /// </summary>
        public static string BackCamera {
            get {
                return ResourceManager.GetString("BackCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Now!.
        /// </summary>
        public static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string Configuration {
            get {
                return ResourceManager.GetString("Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Extend your trial from 3 days to 10 Days, Rate this app 5 stars, and leave a positive comment..
        /// </summary>
        public static string ExtendTrial {
            get {
                return ResourceManager.GetString("ExtendTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash Off.
        /// </summary>
        public static string FlashOff {
            get {
                return ResourceManager.GetString("FlashOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flash On.
        /// </summary>
        public static string FlashOn {
            get {
                return ResourceManager.GetString("FlashOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus Off.
        /// </summary>
        public static string FocusOff {
            get {
                return ResourceManager.GetString("FocusOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus On.
        /// </summary>
        public static string FocusOn {
            get {
                return ResourceManager.GetString("FocusOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Front Camera.
        /// </summary>
        public static string FrontCamera {
            get {
                return ResourceManager.GetString("FrontCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Preview:.
        /// </summary>
        public static string ImagePreview {
            get {
                return ResourceManager.GetString("ImagePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Screen.
        /// </summary>
        public static string MainScreen {
            get {
                return ResourceManager.GetString("MainScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Screen Shot Selected.
        /// </summary>
        public static string NoScreenShotSelected {
            get {
                return ResourceManager.GetString("NoScreenShotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Now.
        /// </summary>
        public static string NotNow {
            get {
                return ResourceManager.GetString("NotNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Counter Off.
        /// </summary>
        public static string PictureCounterOff {
            get {
                return ResourceManager.GetString("PictureCounterOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture Counter On.
        /// </summary>
        public static string PictureCounterOn {
            get {
                return ResourceManager.GetString("PictureCounterOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase.
        /// </summary>
        public static string PurchaseButton {
            get {
                return ResourceManager.GetString("PurchaseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string RateButton {
            get {
                return ResourceManager.GetString("RateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Off.
        /// </summary>
        public static string SoundOff {
            get {
                return ResourceManager.GetString("SoundOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound On.
        /// </summary>
        public static string SoundOn {
            get {
                return ResourceManager.GetString("SoundOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1:  If you haven&apos;t taken any screen shots on your phone, you will need to take a screen shot to use as the spy camera shutter button.  To take a screen shot, press the home button and the power button at the same time.  You can take a screen shot from any screen of any application on your phone..
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2:  Go to the configuration screen.  Choose the screenshot that you wish to use as the background for the button to take pictures.  You can also configure other camera settings on this screen..
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3:  Go to the main screen.  You should now see your screenshot.  To take a picture, simply tap the screen. This typically takes about 1.5 seconds depending on focus settings, as well as which phone you own..
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 4:To view your picture, tap and slide to the left or right on the main screen.  Your picture will also be stored in your media library..
        /// </summary>
        public static string Step4 {
            get {
                return ResourceManager.GetString("Step4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taking Picture.
        /// </summary>
        public static string TakingPictureText {
            get {
                return ResourceManager.GetString("TakingPictureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Has Expired..
        /// </summary>
        public static string TrialExpired {
            get {
                return ResourceManager.GetString("TrialExpired", resourceCulture);
            }
        }
    }
}
